version: '3'
services:
  db:
    build: .
    environment:
      POSTGRES_DB: sseguro
      POSTGRES_USER: root
      POSTGRES_PASSWORD: ruteo
    ports:
      - "5432:5432"
    volumes:
      - my_dbdata:/var/lib/postgresql/data
    # Descomenta la siguiente línea si tienes scripts de inicialización personalizados
    # - ./initdb.d:/docker-entrypoint-initdb.d

volumes:
  my_dbdata:
