version: '3.8'

services:
  postgis:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: postgis_container
    environment:
      POSTGRES_DB: ruteo
      POSTGRES_USER: root
      POSTGRES_PASSWORD: ruteo
    ports:
      - "5432:5432"
    volumes:
      - postgis_data:/var/lib/postgresql/data
      - ./install_pgrouting.sh:/docker-entrypoint-initdb.d/install_pgrouting.sh

volumes:
  postgis_data:
